Should not fail tmux ls

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -41,7 +41,7 @@ jobs:
           echo 'OS: $(uname -a)'
           echo 'Uptime: $(uptime -p)'
           docker ps
-          tmux ls
+          tmux ls || true  # Won't fail if no sessions exist
           
           cd ~/agent_api
           git fetch --all --tags
